Fix/stop connector jobs
Sanketika-Obsrv/obsrv-api-service pull request #264
Opened 2024-10-25 09:15 UTC by SurabhiAngadi

2024-10-25 09:20 UTC, SanthoshVasabhaktula requested changes

2024-10-25 09:20 UTC, SanthoshVasabhaktula commented on command-service/src/command/connector_command.py
> +                    for job in jobs.splitlines()[1:]:
1. No need to compare against dataset as the query filters only dataset specific connectors
2. Filter out only spark jobs from the active connectors
3. No need of nested loops. once alls the jobs are fetch, check if the connector is in the jobs list and then uninstall it

2024-10-29 10:38 UTC, anandp504 approved these changes
We need to revisit the logic of uninstalling and reinstalling the cronjob for a connector instance. We can just perform a helm upgrade --install as the release name is going to be the instance id, i.e. `datasetId-connectorType`. 
Approved 👍

2024-10-29 11:03 UTC, anandp504 approved these changes
Approved 👍

2024-10-29 11:04 UTC, anandp504 submitted a review, later dismissed
Approved 👍

2024-10-29 13:34 UTC, anandp504 approved these changes
Approved 👍

2024-10-30 06:36 UTC, SanthoshVasabhaktula approved these changes

2024-10-30 06:37 UTC, SanthoshVasabhaktula approved these changes

2024-10-30 06:37 UTC, SanthoshVasabhaktula submitted a review, later dismissed

2024-10-30 06:40 UTC, anandp504 submitted a review, later dismissed
Approved 👍

2024-10-30 06:41 UTC, HarishGangula submitted a review, later dismissed

2024-10-30 06:43 UTC, closed without merging